version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: intcomex-postgres
    environment:
      POSTGRES_DB: intcomex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  intcomex-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intcomex-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/intcomex_api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
